trueDomains = ['facebook', "messenger", "instagram", "google", "microsoft", "netflix", "paypal", "steampowered",
                   "twitter", "tiktok", "playstation", "twitch", "pinterest", "linkedin", "snapchat", "quora", "ebay",
                   "spotify", "proton", "reddit", "adobe", "badoo", "deviantart", "supercell", "ajio", "garena", "jio",
                   "pubg", "telegram", "youtube", "airtel", "rockstargames", "live", "olacabs", "origin", "amazon",
                   "mozilla", "amazon", "dropbox", "yahoo", "wordpress", "yandex", "vk", "stackoverflow", "mediafire",
                   "xbox", "gitlab", "github", "apple", "icloud", "myspace", "vimeo", "coinmarketcap", "verizon",
                   "roblox", "discord", "ubereats", "zomato", "whatsapp", "hotstar", "paytm", "mobikwik", "phonepe",
                   "teachable", "flipkart", "tracxn", "aminoapps", "bitcoin","ccn","t","youtube","sanji","zoro",
                   "baidu","wikipedia","instagram","facebook","similarweb","tiktok","live","openai" ,"linkedin",
                   "prime","docomo","dzen","naver","samsung","turbopages","mail","microsoftonline","weather",
                   "pininterest","qq","zoom","quora","duckduckgo","aajtak","globo","ebay","msn","bing",
                   "instructure","walmart","zillow","etsy","indeed","accuweather","aol","imdb","craigslist","t-mobile",
                   "canva","realtor","wellsfargo","lowes","ticketmaster","fedex","tumbir","homedepot","biospot","patreon",
                   "rbi","radiogarden","justwatch","buzzfeed","photopea","forvo","futureme","fotoforensics","ligthningmaps",
                   "pointerpointer","nullschools","naturalreaders","all8","futuretimeline","archive","redmi"]